/* Generated By:JJTree: Do not edit this line. ASTADDSUB.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADDSUB extends SimpleNode {
  public ASTADDSUB(int id) {
    super(id);
  }

  public ASTADDSUB(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d697e6fe9b484f3f6af7114a454fc884 (do not edit this line) */
