/* Generated By:JJTree: Do not edit this line. ASTASSIGNMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSIGNMENT extends SimpleNode {
  public ASTASSIGNMENT(int id) {
    super(id);
  }

  public ASTASSIGNMENT(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51da7821b067114d91c30306b1ba3e74 (do not edit this line) */
