/* Generated By:JJTree: Do not edit this line. ASTADDSUB.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADDSUB extends SimpleNode {
  public ASTADDSUB(int id) {
    super(id);
  }

  public ASTADDSUB(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a2486460f60f36ba69028b4ebe504c6 (do not edit this line) */
