/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBlockStatement extends SimpleNode {
  public ASTBlockStatement(int id) {
    super(id);
  }

  public ASTBlockStatement(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ccdff18161279739aa835d32d8a5a305 (do not edit this line) */
