/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class ASTBooleanLiteral extends SimpleNode {
  public String value;
  public int line;

  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(Jmm p, int id) {
    super(p, id);
  }

  public String toString(){
    return value;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dbca36c6f2fdd2f7c70fae3d7fb4df5c (do not edit this line) */
