/* Generated By:JJTree: Do not edit this line. ASTBODY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBODY extends SimpleNode {
  public ASTBODY(int id) {
    super(id);
  }

  public ASTBODY(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=746797b9ea473c2dfc3c9eb1a933bb69 (do not edit this line) */
