/* Generated By:JJTree: Do not edit this line. ASTBODY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBODY extends SimpleNode {
  public ASTBODY(int id) {
    super(id);
  }

  public ASTBODY(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3d075d118b6c77fd59fc28f504d4c3e (do not edit this line) */
