/* Generated By:JJTree: Do not edit this line. ASTCastLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCastLookahead extends SimpleNode {
  public ASTCastLookahead(int id) {
    super(id);
  }

  public ASTCastLookahead(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e506a6820dd30e6084fd2c9fef649dab (do not edit this line) */
