/* Generated By:JJTree: Do not edit this line. ASTCONSTRUCTOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class ASTCONSTRUCTOR extends SimpleNode {
  public ASTCONSTRUCTOR(int id) {
    super(id);
  }

  public ASTCONSTRUCTOR(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1171e0e940ffa3e995571f988c308bde (do not edit this line) */
