/* Generated By:JJTree: Do not edit this line. ASTConstructorDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConstructorDeclaration extends SimpleNode {
  private String name;
  public ASTConstructorDeclaration(int id) {
    super(id);
  }

  public ASTConstructorDeclaration(Jmm p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return  "Constructor: " + name ;
  }

}
/* JavaCC - OriginalChecksum=c1614355775a31118bc17974e275abba (do not edit this line) */
