/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  private String name;

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Jmm p, int id) {
    super(p, id);
  }

    /**From documentation*/
    public void setName(String n) {
        name = n;
    }

    /**
     * {@inheritDoc}
     * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
     */
    public String toString() {
        return "Class [ " + name + " ]";
    }

}
/* JavaCC - OriginalChecksum=de93fed517ebd8fb13c9fe84a844e1ce (do not edit this line) */
