/* Generated By:JJTree: Do not edit this line. ASTINIT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINIT extends SimpleNode {
  public ASTINIT(int id) {
    super(id);
  }

  public ASTINIT(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=556ce387c6d6b8932652a4d04ac67ade (do not edit this line) */
