/* Generated By:JJTree: Do not edit this line. ASTInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInitializer extends SimpleNode {
  public ASTInitializer(int id) {
    super(id);
  }

  public ASTInitializer(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b6718e53e94a657509c00c1b5665da6 (do not edit this line) */
