/* Generated By:JJTree: Do not edit this line. ASTLESSTHEN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESSTHEN extends SimpleNode {
  public ASTLESSTHEN(int id) {
    super(id);
  }

  public ASTLESSTHEN(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e9598eedcffcbd1afc069055bc7e144 (do not edit this line) */
