/* Generated By:JJTree: Do not edit this line. ASTLESSTHEN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESSTHEN extends SimpleNode {
  public ASTLESSTHEN(int id) {
    super(id);
  }

  public ASTLESSTHEN(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=12df40f9ee7ace879f8729dcfc26dc44 (do not edit this line) */
