/* Generated By:JJTree: Do not edit this line. ASTLessThen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThen extends SimpleNode {
  public ASTLessThen(int id) {
    super(id);
  }

  public ASTLessThen(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dea5e2b6fc8eeb887c172dabc56bc071 (do not edit this line) */
