/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMethodDeclaration extends SimpleNode {
    private String name;
    private String type;


    public ASTMethodDeclaration(int id) {
        super(id);
    }

    public ASTMethodDeclaration(Jmm p, int id) {
        super(p, id);
    }

    public void setType(String n) {
        type = n;
    }

    public void setTyope(String n){
        type = n;
    }

    /**From documentation*/
     public void setName(String n) {
        name = n;
    }

    /**From documentation*/
    public String toString() {
        return "Metodo [ " + type + " "  + name + " ]";
    }

}
/* JavaCC - OriginalChecksum=d5ee27a2b7b420af3112231d3c4175f5 (do not edit this line) */
