/* Generated By:JJTree: Do not edit this line. ASTMultiDiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultiDiv extends SimpleNode {
  public ASTMultiDiv(int id) {
    super(id);
  }

  public ASTMultiDiv(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe9eac6f6d6a89234ca3d81dcbd7355c (do not edit this line) */
