/* Generated By:JJTree: Do not edit this line. ASTMETHOD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD extends SimpleNode {
  public ASTMETHOD(int id) {
    super(id);
  }

  public ASTMETHOD(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d6ca3c91d9e601cc37eb7afd26f44181 (do not edit this line) */
