/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodDeclarator extends SimpleNode {
  private String name;

  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(Jmm p, int id) {
    super(p, id);
  }

    public void setName(String n) {
        name = n;
    }

    public String toString() {
        return  name;
    }
}
/* JavaCC - OriginalChecksum=a95502136eda7326ad9f16d9d60726e6 (do not edit this line) */
