/* Generated By:JJTree: Do not edit this line. ASTNestedClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNestedClassDeclaration extends SimpleNode {
  public ASTNestedClassDeclaration(int id) {
    super(id);
  }

  public ASTNestedClassDeclaration(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2fe495d4bfa68a559cae6d5b0c7e5e0 (do not edit this line) */
