/* Generated By:JJTree: Do not edit this line. ASTNovos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNovos extends SimpleNode {
  public ASTNovos(int id) {
    super(id);
  }

  public ASTNovos(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f429ef6ee796035c3c142a9f776e191 (do not edit this line) */
