/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class ASTPrimarySuffix extends SimpleNode {
  public int line;
  public String value;

  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(Jmm p, int id) {
    super(p, id);
  }

public String toString(){
    return value;
}
  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=470c95660c7ec84d1f8d3f5f2365eb33 (do not edit this line) */
