/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimarySuffix extends SimpleNode {
  private String name;

  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(Jmm p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "VarId: [" + name + "]";
  }
}
/* JavaCC - OriginalChecksum=9d0c7fdf54558dfe7f29938174736548 (do not edit this line) */
