/* Generated By:JJTree: Do not edit this line. ASTStatementExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementExpressionList extends SimpleNode {
  public ASTStatementExpressionList(int id) {
    super(id);
  }

  public ASTStatementExpressionList(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f21e8d2c793d125a74e1754d942601df (do not edit this line) */
