/* Generated By:JJTree: Do not edit this line. ASTSolveAmbiguityInPointExp1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSolveAmbiguityInPointExp1 extends SimpleNode {
  public ASTSolveAmbiguityInPointExp1(int id) {
    super(id);
  }

  public ASTSolveAmbiguityInPointExp1(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d738a41ac08bd78b6ab8ee7fda7a2be (do not edit this line) */
