/* Generated By:JJTree: Do not edit this line. ASTUnaryExpressionNotPlusMinus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaryExpressionNotPlusMinus extends SimpleNode {
  public ASTUnaryExpressionNotPlusMinus(int id) {
    super(id);
  }

  public ASTUnaryExpressionNotPlusMinus(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=71877f7b4d78215ed6e4e2f62287a318 (do not edit this line) */
