/* Generated By:JJTree: Do not edit this line. ASTVariableInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableInitializer extends SimpleNode {
  public ASTVariableInitializer(int id) {
    super(id);
  }

  public ASTVariableInitializer(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8afef3aae8e2fd824b1fe41534f5c348 (do not edit this line) */
