/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTVariableDeclaratorId extends SimpleNode {
    private String name;

    public ASTVariableDeclaratorId(int id) {
        super(id);
    }

    public ASTVariableDeclaratorId(Jmm p, int id) {
        super(p, id);
    }

    public void setName(String n) {
        name = n;
    }

    public String toString() {
        return "VarId: [" + name + "]";
    }
}
/* JavaCC - OriginalChecksum=b70e43608c68bf87fcc6211345732301 (do not edit this line) */
