/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableDeclarator extends SimpleNode {

  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e46a256b581a8f56b28f3acbba2fb3a (do not edit this line) */
