/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d51110370f944119537493df36b9aabc (do not edit this line) */
