/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWHILE extends SimpleNode {
  public ASTWHILE(int id) {
    super(id);
  }

  public ASTWHILE(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=befd3ebc05d12bf4693560bf7839daa8 (do not edit this line) */
