/* Generated By:JavaCC: Do not edit this line. JmmVisitor.java Version 5.0 */
public interface JmmVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTUnmodifiedClassDeclaration node, Object data);
  public Object visit(ASTINICIALIZACAO node, Object data);
  public Object visit(ASTNCD node, Object data);
  public Object visit(ASTCONSTRUCTOR node, Object data);
  public Object visit(ASTMETODO node, Object data);
  public Object visit(ASTFD node, Object data);
  public Object visit(ASTMethodDeclarationLookahead node, Object data);
  public Object visit(ASTINIT node, Object data);
  public Object visit(ASTVariableDeclaratorId node, Object data);
  public Object visit(ASTMethodDeclaration node, Object data);
  public Object visit(ASTMethodDeclarator node, Object data);
  public Object visit(ASTConstructorDeclaration node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTPrimitiveType node, Object data);
  public Object visit(ASTResultType node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTASSIGNMENT node, Object data);
  public Object visit(ASTLESSTHEN node, Object data);
  public Object visit(ASTADDSUB node, Object data);
  public Object visit(ASTDIVMULT node, Object data);
  public Object visit(ASTCastLookahead node, Object data);
  public Object visit(ASTPrimarySuffix node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTIntegerLiteral node, Object data);
  public Object visit(ASTBooleanLiteral node, Object data);
  public Object visit(ASTIF node, Object data);
  public Object visit(ASTCONDITION node, Object data);
  public Object visit(ASTSTATEMENT node, Object data);
  public Object visit(ASTELSE node, Object data);
  public Object visit(ASTWHILE node, Object data);
  public Object visit(ASTBODY node, Object data);
  public Object visit(ASTRETURN node, Object data);
}
/* JavaCC - OriginalChecksum=fec3d8bd6d8561c2657e22d60c05951f (do not edit this line) */
