/* Generated By:JJTree: Do not edit this line. ASTAddSub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTAddSub extends SimpleNode {
  public ASTAddSub(int id) {
    super(id);
  }

  public ASTAddSub(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe6248e6ff4f19bb6aaf0ff68da00c81 (do not edit this line) */
