/* Generated By:JJTree: Do not edit this line. ASTExp1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTExp1 extends SimpleNode {
  public ASTExp1(int id) {
    super(id);
  }

  public ASTExp1(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=943b9c2c79770f972502d9df5eb2df01 (do not edit this line) */
