/* Generated By:JJTree: Do not edit this line. ASTLessThan.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTLessThan extends SimpleNode {
  public ASTLessThan(int id) {
    super(id);
  }

  public ASTLessThan(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99e8a52b9d18a80ebc951b955b41b3b7 (do not edit this line) */
