/* Generated By:JJTree: Do not edit this line. ASTMultDiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTMultDiv extends SimpleNode {
  public ASTMultDiv(int id) {
    super(id);
  }

  public ASTMultDiv(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac14cc23552c0cd7c327368a0c093e5e (do not edit this line) */
