/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationArgs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTMethodDeclarationArgs extends SimpleNode {
  public ASTMethodDeclarationArgs(int id) {
    super(id);
  }

  public ASTMethodDeclarationArgs(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b58be2283826b695a195b697d9fea438 (do not edit this line) */
