/* Generated By:JJTree: Do not edit this line. ASTNovos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTNovos extends SimpleNode {
  public ASTNovos(int id) {
    super(id);
  }

  public ASTNovos(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=795a985c8cda82e7ebff3cc2ee9dfed0 (do not edit this line) */
