/* Generated By:JJTree: Do not edit this line. ASTSolveAmbiguityInPointExp1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTSolveAmbiguityInPointExp1 extends SimpleNode {
  public ASTSolveAmbiguityInPointExp1(int id) {
    super(id);
  }

  public ASTSolveAmbiguityInPointExp1(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea192f75d0c796b7bec076b05b27d945 (do not edit this line) */
