/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjtree;

public
class ASTVarDeclaration extends SimpleNode {
  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1e519bbf95fe73351c2903fe72e4c40 (do not edit this line) */
