/* Generated By:JJTree: Do not edit this line. ASTASSIGNMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTASSIGNMENT extends SimpleNode {
  public ASTASSIGNMENT(int id) {
    super(id);
  }

  public ASTASSIGNMENT(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ca8d30f2c2bea9c03d2f025ec1966015 (do not edit this line) */
