package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTArrayDimsAndInits.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayDimsAndInits extends SimpleNode {
  public ASTArrayDimsAndInits(int id) {
    super(id);
  }

  public ASTArrayDimsAndInits(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f8215c6c3a718f27fd8f4104de4075e0 (do not edit this line) */
