/* Generated By:JJTree: Do not edit this line. ASTCONSTRUCTOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTCONSTRUCTOR extends SimpleNode {
  public ASTCONSTRUCTOR(int id) {
    super(id);
  }

  public ASTCONSTRUCTOR(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49b3170b17379ebcec8766504af81890 (do not edit this line) */
