package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTCONSTRUCTOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCONSTRUCTOR extends SimpleNode {
  public ASTCONSTRUCTOR(int id) {
    super(id);
  }

  public ASTCONSTRUCTOR(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f2e714109d1509cd4d9f2c424e9aa29 (do not edit this line) */
