/* Generated By:JJTree: Do not edit this line. ASTCONDITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTCONDITION extends SimpleNode {
  public ASTCONDITION(int id) {
    super(id);
  }

  public ASTCONDITION(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2ccf8c884715af84a94d13ecf3b9bcd4 (do not edit this line) */
