package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTClassBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassBody extends SimpleNode {
  public ASTClassBody(int id) {
    super(id);
  }

  public ASTClassBody(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2cd01a9401c1dcbf693a1bcca6764ab (do not edit this line) */
