package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTDIVMULT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDIVMULT extends SimpleNode {
  public ASTDIVMULT(int id) {
    super(id);
  }

  public ASTDIVMULT(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=08549d0743e93663a67aab46d4738ab4 (do not edit this line) */
