/* Generated By:JJTree: Do not edit this line. ASTDIVMULT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTDIVMULT extends SimpleNode {
  public ASTDIVMULT(int id) {
    super(id);
  }

  public ASTDIVMULT(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e9dccac349cfafd9e747fc58057c3fee (do not edit this line) */
