package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTEQUAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQUAL extends SimpleNode {
  public ASTEQUAL(int id) {
    super(id);
  }

  public ASTEQUAL(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=527d274c8cab7ba2b230e7d9e0b8b402 (do not edit this line) */
