package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTELSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSE extends SimpleNode {
  public ASTELSE(int id) {
    super(id);
  }

  public ASTELSE(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad0f3243bed3f43e1ab19794acb4e257 (do not edit this line) */
