package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTelseStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTelseStatement extends SimpleNode {
  public ASTelseStatement(int id) {
    super(id);
  }

  public ASTelseStatement(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e956264e8de7cb81909e6ab19b6df9c (do not edit this line) */
