package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTFormalParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFormalParameters extends SimpleNode {
  public ASTFormalParameters(int id) {
    super(id);
  }

  public ASTFormalParameters(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aebc0b418810297af093b3b32b3d8141 (do not edit this line) */
