package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTFieldDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFieldDeclaration extends SimpleNode {
  public ASTFieldDeclaration(int id) {
    super(id);
  }

  public ASTFieldDeclaration(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e000c9194d3257fd2f98ea40f2e303f (do not edit this line) */
