package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTFormalParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFormalParameter extends SimpleNode {
  public ASTFormalParameter(int id) {
    super(id);
  }

  public ASTFormalParameter(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=beea2144c4fa6b27d3dc7213ffed35e0 (do not edit this line) */
