package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTLESSTHAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESSTHAN extends SimpleNode {
  public ASTLESSTHAN(int id) {
    super(id);
  }

  public ASTLESSTHAN(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7734d792cdab50e8f740f3231da8798 (do not edit this line) */
