package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLocalVariableDeclaration extends SimpleNode {
  public ASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public ASTLocalVariableDeclaration(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=08ae86884be0360fdcfafc13a613b8fc (do not edit this line) */
