/* Generated By:JJTree: Do not edit this line. ASTMETODO.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTMETODO extends SimpleNode {
  public ASTMETODO(int id) {
    super(id);
  }

  public ASTMETODO(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6c75daf7ff0b0fd96f567c9c1c6b66d1 (do not edit this line) */
