package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTMultDiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultDiv extends SimpleNode {
  public ASTMultDiv(int id) {
    super(id);
  }

  public ASTMultDiv(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=022c1d89003a1fabd22f5c44f4c223e6 (do not edit this line) */
