package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTMETODO.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETODO extends SimpleNode {
  private String name;
  private int line = 0;


  public ASTMETODO(int id) {
    super(id);
  }

  public ASTMETODO(Jmm p, int id) {
    super(p, id);
  }
  public void setName(String n) {
    name = n;
}

public String toString() {
    return  name;
}
public String getName(){
  return name;
}
public int getLine(){
  return line;
}

}
/* JavaCC - OriginalChecksum=43d90eb6fedb6814bd6e33b586aba3f7 (do not edit this line) */
