package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationdInside.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodDeclarationdInside extends SimpleNode {
  public ASTMethodDeclarationdInside(int id) {
    super(id);
  }

  public ASTMethodDeclarationdInside(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=76b5940aabc3abfb13b401420b605504 (do not edit this line) */
