package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMethodDeclarationLookahead extends SimpleNode {
    private String name;

    public ASTMethodDeclarationLookahead(int id) {
        super(id);
    }

    public ASTMethodDeclarationLookahead(Jmm p, int id) {
        super(p, id);
    }

    public void setName(String n) {
        name = n;
    }

    public String toString() {
        return "MtLLL: [" + name + "]";
    }
}
/* JavaCC - OriginalChecksum=6c2b24d5af11a0683f2e84a4b57fb0f6 (do not edit this line) */
