/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTMethodDeclarationLookahead extends SimpleNode {
  public ASTMethodDeclarationLookahead(int id) {
    super(id);
  }

  public ASTMethodDeclarationLookahead(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e23779e9c7ea0c2ace116bcaaa1a2360 (do not edit this line) */
