package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationArgs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodDeclarationArgs extends SimpleNode {
  public ASTMethodDeclarationArgs(int id) {
    super(id);
  }

  public ASTMethodDeclarationArgs(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84dc8be184bed5c537b352b88b4b8fa6 (do not edit this line) */
