package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTNameList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNameList extends SimpleNode {
  public ASTNameList(int id) {
    super(id);
  }

  public ASTNameList(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=146265a8abb7221c8accb338c4a7d815 (do not edit this line) */
