/* Generated By:JJTree: Do not edit this line. ASTResultType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTResultType extends SimpleNode {
  public ASTResultType(int id) {
    super(id);
  }

  public ASTResultType(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=67b36aa5a64377c1f2c4b4475c47770c (do not edit this line) */
