package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTRETURN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRETURN extends SimpleNode {
  public ASTRETURN(int id) {
    super(id);
  }

  public ASTRETURN(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cef83fa285173927ef212d8fa7920ad4 (do not edit this line) */
