package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTSolveAmbiguityInStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSolveAmbiguityInStatement extends SimpleNode {
  public ASTSolveAmbiguityInStatement(int id) {
    super(id);
  }

  public ASTSolveAmbiguityInStatement(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a9800675fba97b2122c6366cf13560e (do not edit this line) */
