package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTSTATEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENT extends SimpleNode {
  public ASTSTATEMENT(int id) {
    super(id);
  }

  public ASTSTATEMENT(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c574219d5146472fc733de8726d52ce1 (do not edit this line) */
