package AST_files;

/* Generated By:JJTree: Do not edit this line. ASTUnmodifiedClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnmodifiedClassDeclaration extends SimpleNode {
  private String name;

  public ASTUnmodifiedClassDeclaration(int id) {
    super(id);
  }

  public ASTUnmodifiedClassDeclaration(Jmm p, int id) {
    super(p, id);
  }

   public void setName(String n) {
        name = n;
    }

    public String toString() {
        return "Classe: [" + name + "]";
    }
}
/* JavaCC - OriginalChecksum=9feb76a1a6fe5e6d88b605d3a9190d1f (do not edit this line) */
