/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST_files;

public
class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(Jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JmmVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=894cf9d2ab8908afaa974024c6f87d6e (do not edit this line) */
