/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 5.0 */
package AST_files;

public interface JmmTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTUNMODIFIEDCLASSDECLARATION = 2;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 3;
  public int JJTINIT = 4;
  public int JJTVARIABLEDECLARATORID = 5;
  public int JJTMETODO = 6;
  public int JJTMETHODDECLARATOR = 7;
  public int JJTCONSTRUCTORDECLARATION = 8;
  public int JJTTYPE = 9;
  public int JJTPRIMITIVETYPE = 10;
  public int JJTNAME = 11;
  public int JJTASSIGNMENT = 12;
  public int JJTLESSTHEN = 13;
  public int JJTADDSUB = 14;
  public int JJTDIVMULT = 15;
  public int JJTCASTLOOKAHEAD = 16;
  public int JJTLITERAL = 17;
  public int JJTINTEGERLITERAL = 18;
  public int JJTIF = 19;
  public int JJTCONDITION = 20;
  public int JJTSTATEMENT = 21;
  public int JJTELSE = 22;
  public int JJTWHILE = 23;
  public int JJTBODY = 24;
  public int JJTRETURN = 25;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "UnmodifiedClassDeclaration",
    "MethodDeclarationLookahead",
    "INIT",
    "VariableDeclaratorId",
    "METODO",
    "MethodDeclarator",
    "ConstructorDeclaration",
    "Type",
    "PrimitiveType",
    "Name",
    "ASSIGNMENT",
    "LESSTHEN",
    "ADDSUB",
    "DIVMULT",
    "CastLookahead",
    "Literal",
    "IntegerLiteral",
    "IF",
    "CONDITION",
    "STATEMENT",
    "ELSE",
    "WHILE",
    "BODY",
    "RETURN",
  };
}
/* JavaCC - OriginalChecksum=59b7527df5d86f6e6ed47a8a3570d6ab (do not edit this line) */
