/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 5.0 */
package AST_files;

public interface JmmTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTUNMODIFIEDCLASSDECLARATION = 2;
  public int JJTINICIALIZACAO = 3;
  public int JJTNCD = 4;
  public int JJTCONSTRUCTOR = 5;
  public int JJTMETODO = 6;
  public int JJTFD = 7;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 8;
  public int JJTINIT = 9;
  public int JJTVARIABLEDECLARATORID = 10;
  public int JJTMETHODDECLARATION = 11;
  public int JJTMETHODDECLARATOR = 12;
  public int JJTCONSTRUCTORDECLARATION = 13;
  public int JJTTYPE = 14;
  public int JJTPRIMITIVETYPE = 15;
  public int JJTRESULTTYPE = 16;
  public int JJTNAME = 17;
  public int JJTASSIGNMENT = 18;
  public int JJTLESSTHEN = 19;
  public int JJTADDSUB = 20;
  public int JJTDIVMULT = 21;
  public int JJTCASTLOOKAHEAD = 22;
  public int JJTPRIMARYSUFFIX = 23;
  public int JJTLITERAL = 24;
  public int JJTINTEGERLITERAL = 25;
  public int JJTBOOLEANLITERAL = 26;
  public int JJTIF = 27;
  public int JJTCONDITION = 28;
  public int JJTSTATEMENT = 29;
  public int JJTELSE = 30;
  public int JJTWHILE = 31;
  public int JJTBODY = 32;
  public int JJTRETURN = 33;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "UnmodifiedClassDeclaration",
    "INICIALIZACAO",
    "NCD",
    "CONSTRUCTOR",
    "METODO",
    "FD",
    "MethodDeclarationLookahead",
    "INIT",
    "VariableDeclaratorId",
    "MethodDeclaration",
    "MethodDeclarator",
    "ConstructorDeclaration",
    "Type",
    "PrimitiveType",
    "ResultType",
    "Name",
    "ASSIGNMENT",
    "LESSTHEN",
    "ADDSUB",
    "DIVMULT",
    "CastLookahead",
    "PrimarySuffix",
    "Literal",
    "IntegerLiteral",
    "BooleanLiteral",
    "IF",
    "CONDITION",
    "STATEMENT",
    "ELSE",
    "WHILE",
    "BODY",
    "RETURN",
  };
}
/* JavaCC - OriginalChecksum=039f3134657aca7f914738d4b680613e (do not edit this line) */
